name: CI

#on: [push]

# 在 master 分支发生 push 事件时触发。
on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout # 步骤1：拉取代码
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: run deploy.sh # 步骤3：执行脚本 deploy.sh
        env: # 设置环境变量，未设置则不运行
          GITHUB_TOKEN: ${{ secrets.VDOING_ACCESS_TOKEN }} # GitHub toKen 私密变量
          SSH_PRIVATE_KEY: ${{ SECRETS.GITEE_RSA_PRIVATE_KEY }} # Gitee token 私钥
          # CODING_TOKEN: ${{ secrets.VDOING_CODING_TOKEN }}
        run: npm install && npm run deploy # 执行 deploy.sh 脚本，位于项目根目录

#      - name: Push Master To Gitee # 步骤4： GitHub 内容同步到 Gitee，同步仓库是 maser
#        uses: wearerequired/git-mirror-action@master
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
#        with: # 从源到目的地
#          source-repo: 'git@github.com:oliver556/oliver556.github.io.git' # GitHub 仓库地址
#          desitination-repo: '' # Gitee 仓库地址
#
#      - name: Build Gitee Pages # 步骤5：自动部署到 Gitee Pages
#        uses: oliver556/gitee-pages-action@master
#        with:
#          # 注意替换为你的 Gitee 用户名
#          gitee-username: oliver556
#          # 注意在 Settings -> Secrets 配置 GITEE_PASSWORD
#          gitee-password: ${{ secrets.GITEE_PASSWORD }}
#          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
#          gitee-repo: oliver556/notes-blog
#          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
#          branch: gh-pages

      # - name: Build and Deploy # 步骤3 （只提交到github可以使用这个步骤）
      #   uses: JamesIves/github-pages-deploy-action@master # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
      #   env: # 设置环境变量
      #     Vdoing: ${{ secrets.Vdoing }} # toKen私密变量
      #     BASE_BRANCH: master # 要部署的文件夹所在的分支.
      #     BRANCH: gh-pages # 部署到的分支
      #     FOLDER: docs/.vuepress/dist # 要部署的文件夹.
      #     BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist && echo 'xugaoyi.com' > CNAME && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）
